target_machine:
  - x86_64
  - aarch64
  - powerpc64le
  - s390x
centos_machine:
  - x86_64
  - aarch64
  - ppc64le
  - s390x
cross_target_platform:
  - linux-64
  - linux-aarch64
  - linux-ppc64le
  - linux-s390x

alma_version:
  - "8.9"
glibc_version:
  - "2.28"
kernel_headers_version:
  - "4.18.0"
# glibc artefacts have two build numbers plus the alma version, e.g.
#   2.28-236.el8_9.13.x86_64.rpm
#   ↑    ↑     ↑   ↑
#   └glibc_ver └alma_version
#        └build1   └build2
glibc_build1:
  - "236"
glibc_build2:
  - "13"
kernel_headers_build:
  - "513.24.1"
# nss-* versions need to be set in meta.yaml (and/or update.py)

ctng_vendor:
  - conda

zip_keys:
  - - target_machine
    - cross_target_platform
    - centos_machine
